// Code generated by "stringer -type MatMode"; DO NOT EDIT.

package matlab

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[r-0]
	_ = x[u-1]
	_ = x[w-2]
	_ = x[w4-3]
	_ = x[w6-4]
	_ = x[wL-5]
	_ = x[w7-6]
	_ = x[wz-7]
	_ = x[w7_3-8]
}

const _MatMode_name = "ruww4w6wLw7wzw7_3"

var _MatMode_index = [...]uint8{0, 1, 2, 3, 5, 7, 9, 11, 13, 17}

func (i MatMode) String() string {
	if i < 0 || i >= MatMode(len(_MatMode_index)-1) {
		return "MatMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MatMode_name[_MatMode_index[i]:_MatMode_index[i+1]]
}
