// Code generated by "stringer -type MclFunction -linecomment"; DO NOT EDIT.

package mclmcr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[mclmcrInitialize-0]
	_ = x[mclInitializeApplication-1]
	_ = x[mclTerminateApplication-2]
	_ = x[mclGetLastErrorMessage-3]
	_ = x[mclGetLogFileName-4]
}

const _MclFunction_name = "mclmcrInitialize_proxymclInitializeApplication_800_proxymclTerminateApplication_proxymclGetLastErrorMessage_proxymclGetLogFileName_proxy"

var _MclFunction_index = [...]uint8{0, 22, 56, 85, 113, 136}

func (i MclFunction) String() string {
	if i < 0 || i >= MclFunction(len(_MclFunction_index)-1) {
		return "MclFunction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MclFunction_name[_MclFunction_index[i]:_MclFunction_index[i+1]]
}
